### PR TITLE
Batch of commits for Week 19

### PR DESCRIPTION
**Pull request by Draise14**

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
@Draise, as told, there is no need for pull requests anymore. Just commit it to the master. Or click at the Merge button here ;)

**Comment by Draise14** [comment]
Just being careful - prefer the procedure here. I remember screwing up the master once or twice here before!

**Comment by ReinerBforartists** [comment]
You should mention this merge in this issue here though. https://github.com/Bforartists/Manual/issues/260

It is not connected to a task anymore when you do a pull request.

**Comment by ReinerBforartists** [comment]
> Just being careful - prefer the procedure here. I remember screwing up the master once or twice here before!

This is the best way to learn. You will never forget it when you mess it up big time ;)

**Pull request merged**
